// 人情场的人。引擎只读 PEOPLE；CIRCLES 是内容体检用的主团，不进存档。
// 皮肤沿用 campaign.ts 的 demands / veto / budget / maxUnits。立绘走 asset()。
import { asset } from "../../base.ts";
import type { Bond, BondKind, Person } from "../types.ts";

/** 主团。每人只进一团；指向团外的关系算跨团。 */
export const CIRCLES: Record<string, readonly string[]> = {
  counter: ["roman", "suman", "tangke", "fangmin", "qiaowan", "peilan"],
  shen: ["shen", "miduo", "tangtang"],
  wedding: ["anjie", "liangxia", "baijie"],
  parents: ["zhao", "zhaoning", "qianjie"],
  besties: ["heqing", "ruanxiaoman"],
  dance: ["caiaiyi", "linyi", "wulaoshi", "dongayi"],
  dorm: ["xiaoyu", "guyan", "jiangning", "suxiao", "duan"],
  bulk: ["songjie", "hanlei", "chendao"],
  weilo: ["luyao", "zhou", "yenushi"],
  mall: ["ligui", "laokang", "huojie", "lina"],
  gao: ["gaoyuan", "cenning"],
  chen: ["chenke", "tanwan"],
  afternoon: ["mei", "yinxiaojie"],
};

type Link = [string, string, BondKind, number, BondKind, number];

/** 一条写两向。冷暖可以不对称，种类也可以不对称。 */
const LINKS: Link[] = [
  ["roman", "suman", "colleague", 40, "colleague", 15],
  ["roman", "tangke", "colleague", 20, "colleague", 10],
  ["roman", "fangmin", "colleague", 35, "colleague", 20],
  ["roman", "qiaowan", "mentor", 30, "mentor", 50],
  ["roman", "peilan", "colleague", 25, "colleague", 10],
  ["suman", "tangke", "colleague", 35, "colleague", 20],
  ["suman", "fangmin", "colleague", -10, "colleague", 5],
  ["suman", "qiaowan", "mentor", 40, "mentor", 55],
  ["tangke", "fangmin", "colleague", 15, "colleague", 10],
  ["tangke", "qiaowan", "colleague", 25, "colleague", 30],
  ["fangmin", "peilan", "colleague", 40, "colleague", 30],
  ["peilan", "qiaowan", "colleague", 0, "colleague", -5],
  ["roman", "luyao", "rival", -25, "rival", -30],
  ["roman", "huojie", "colleague", 10, "colleague", 25],
  ["roman", "hanlei", "client", 10, "client", 20],
  ["suman", "anjie", "client", 70, "client", 75],
  ["suman", "dongayi", "client", 60, "client", 65],
  ["suman", "mei", "client", 45, "client", 50],
  ["suman", "yenushi", "client", 10, "rival", -10],
  ["tangke", "luyao", "rival", -15, "rival", -15],
  ["tangke", "zhou", "client", 15, "client", 20],
  ["fangmin", "yinxiaojie", "client", 20, "client", 15],
  ["fangmin", "hanlei", "client", 15, "client", 25],
  ["qiaowan", "dongayi", "client", -10, "rival", -20],
  ["qiaowan", "suxiao", "client", 5, "friend", 10],
  ["qiaowan", "yenushi", "colleague", -5, "colleague", -15],
  ["peilan", "huojie", "colleague", 20, "colleague", 15],
  ["peilan", "luyao", "colleague", -5, "colleague", 5],
  ["shen", "miduo", "colleague", 45, "fan", 70],
  ["shen", "tangtang", "mentor", 25, "fan", 80],
  ["shen", "luyao", "rival", -35, "client", 40],
  ["shen", "songjie", "rival", -15, "rival", -5],
  ["miduo", "tangtang", "colleague", 20, "colleague", 15],
  ["miduo", "heqing", "fan", 25, "friend", 30],
  ["miduo", "liangxia", "rival", -10, "rival", -30],
  ["miduo", "wulaoshi", "rival", -25, "rival", -15],
  ["miduo", "cenning", "client", 15, "fan", 40],
  ["tangtang", "xiaoyu", "friend", 20, "friend", 10],
  ["anjie", "liangxia", "friend", 75, "friend", 70],
  ["anjie", "baijie", "client", 55, "client", 40],
  ["anjie", "zhao", "friend", 20, "friend", 25],
  ["liangxia", "baijie", "colleague", 10, "colleague", -5],
  ["baijie", "songjie", "rival", -25, "client", 20],
  ["baijie", "chenke", "client", 5, "client", 10],
  ["zhao", "zhaoning", "family", 80, "family", 35],
  ["zhao", "qianjie", "friend", 20, "friend", 15],
  ["zhao", "linyi", "friend", 30, "friend", 25],
  ["zhaoning", "qianjie", "friend", -8, "friend", 10],
  ["zhaoning", "jiangning", "friend", 40, "friend", 35],
  ["zhaoning", "duan", "friend", 15, "friend", 15],
  ["zhaoning", "tanwan", "friend", 10, "friend", 10],
  ["qianjie", "heqing", "rival", -15, "rival", -10],
  ["qianjie", "chenke", "friend", 5, "friend", 5],
  ["heqing", "ruanxiaoman", "friend", 60, "friend", 40],
  ["heqing", "cenning", "friend", 20, "friend", 20],
  ["ruanxiaoman", "jiangning", "friend", 15, "friend", 15],
  ["ruanxiaoman", "tanwan", "friend", 25, "friend", 30],
  ["caiaiyi", "linyi", "friend", 55, "friend", 50],
  ["caiaiyi", "wulaoshi", "friend", 30, "friend", 10],
  ["caiaiyi", "dongayi", "friend", 45, "friend", 40],
  ["caiaiyi", "songjie", "rival", -20, "client", 30],
  ["caiaiyi", "ligui", "friend", 15, "friend", 20],
  ["linyi", "wulaoshi", "friend", 35, "colleague", 20],
  ["linyi", "dongayi", "friend", 25, "friend", 25],
  ["wulaoshi", "dongayi", "friend", 15, "friend", 20],
  ["wulaoshi", "yinxiaojie", "colleague", 25, "colleague", 10],
  ["guyan", "jiangning", "friend", 50, "friend", 45],
  ["guyan", "suxiao", "friend", 40, "friend", 35],
  ["guyan", "xiaoyu", "friend", 20, "friend", 10],
  ["guyan", "songjie", "friend", -10, "client", 15],
  ["jiangning", "suxiao", "colleague", 20, "friend", 20],
  ["jiangning", "gaoyuan", "colleague", 10, "friend", 25],
  ["xiaoyu", "suxiao", "friend", 30, "friend", 25],
  ["xiaoyu", "duan", "friend", 30, "friend", 35],
  ["xiaoyu", "gaoyuan", "friend", 5, "friend", 10],
  ["duan", "jiangning", "friend", 10, "friend", 10],
  ["duan", "lina", "friend", 20, "friend", 25],
  ["songjie", "hanlei", "rival", -40, "rival", -35],
  ["songjie", "chendao", "colleague", 10, "colleague", -10],
  ["hanlei", "chendao", "colleague", 15, "colleague", 5],
  ["luyao", "zhou", "client", 55, "client", 20],
  ["luyao", "yenushi", "client", 70, "client", 75],
  ["zhou", "yenushi", "friend", 15, "friend", 10],
  ["zhou", "mei", "friend", 25, "friend", 20],
  ["ligui", "lina", "family", 85, "family", 60],
  ["ligui", "laokang", "colleague", 40, "colleague", 45],
  ["ligui", "huojie", "colleague", 10, "colleague", 5],
  ["laokang", "huojie", "colleague", 30, "colleague", 20],
  ["laokang", "lina", "friend", 40, "friend", 35],
  ["laokang", "mei", "friend", 20, "friend", 15],
  ["laokang", "chendao", "colleague", 0, "colleague", 10],
  ["huojie", "lina", "colleague", -10, "colleague", -5],
  ["gaoyuan", "cenning", "partner", 55, "partner", 35],
  ["chenke", "tanwan", "partner", 50, "partner", 45],
  ["mei", "yinxiaojie", "rival", -20, "rival", -15],
];

const DRAFTS: Array<Omit<Person, "bonds">> = [
  {
    id: "shen", name: "沈薇", role: "customer", age: 29,
    descriptor: "熟客博主，对面也认识她",
    tempers: ["proud", "wary"],
    skin: {
      demands: [{ trait: "natural", want: 2, weight: 3 }, { trait: "steady", want: 1, weight: 2 }, { trait: "correct", want: 1, weight: 1 }],
      veto: { trait: "natural", below: 2, note: "一厚就卡粉，镜头里全是粉感" },
      budget: 3200, maxUnits: 3,
    },
    visits: { days: [1, 3, 5, 6, 7], slots: [1, 2], chance: 0.55 },
    secret: { text: "署她名字的那张退货单，不是她退的。", reveal: [{ remembers: "shen", act: "not-my-return" }] },
    voice: {
      greet: "先说好，我不缺粉底。",
      pleased: "这句像判断，不像话术。",
      hurt: "你还是把我往套装上带。",
      praise: "{player}没拿价格替我做判断。",
      complain: "{player}一开口就是品牌话术。{x}要是信了，镜头里全是粉。",
    },
    portrait: asset("/assets/game/customer-shen-consultation.png"),
  },
  {
    id: "mei", name: "梅女士", role: "customer", age: 41,
    descriptor: "下班还要见客户，只留十分钟",
    tempers: ["hasty", "loyal"],
    skin: {
      demands: [{ trait: "soothe", want: 2, weight: 3 }, { trait: "steady", want: 1, weight: 2 }, { trait: "correct", want: 1, weight: 1 }],
      budget: 1800, maxUnits: 1,
    },
    visits: { days: [1, 2, 3, 4, 5], slots: [2], chance: 0.35 },
    voice: {
      greet: "我明早要见客户。别给我一整套。",
      pleased: "就这一支。用法你说短一点。",
      hurt: "我表上没这十分钟了。",
      praise: "{player}知道我赶时间，没加东西。",
      complain: "{player}明明看见我在看表，还在加。",
    },
    portrait: asset("/assets/game/customer-mei-consultation.png"),
  },
  {
    id: "xiaoyu", name: "小雨", role: "customer", age: 22,
    descriptor: "第一次买高端，预算就一千",
    tempers: ["shy", "thrifty"],
    skin: {
      demands: [{ trait: "steady", want: 2, weight: 3 }, { trait: "natural", want: 1, weight: 2 }, { trait: "correct", want: 1, weight: 1 }],
      veto: { trait: "steady", below: 2, note: "活跃痘正在冒，闷一下就爆" },
      budget: 1000, maxUnits: 1,
    },
    visits: { days: [2, 4, 6], slots: [2, 3], chance: 0.4 },
    voice: {
      greet: "我只有一千块。明天面试。",
      pleased: "这一支我付得起，也不会闷。",
      hurt: "我说了一千。你还在往上加。",
      praise: "{player}先问了预算，没让我难堪。",
      complain: "{player}当着别人的面说我预算不够。",
    },
    portrait: asset("/assets/game/customer-xiaoyu-consultation.png"),
  },
  {
    id: "zhao", name: "赵女士", role: "customer", age: 48,
    descriptor: "给女儿买，自己的脸不作数",
    tempers: ["wary", "thrifty"],
    skin: {
      demands: [{ trait: "steady", want: 2, weight: 3 }, { trait: "soothe", want: 2, weight: 2 }],
      veto: { trait: "soothe", below: 2, note: "女儿对香精起反应，先要稳住" },
      budget: 1800, maxUnits: 1,
      buysFor: "zhaoning",
    },
    visits: { days: [3, 6], slots: [1, 2], chance: 0.4 },
    secret: { text: "过敏那一行是女儿自己写的，她记错了一格。", reveal: [{ present: "zhaoning" }, { opinion: "zhaoning", gte: 10 }] },
    voice: {
      greet: "你别看我。东西是买给她的。",
      pleased: "你看了她的单子，没看我的脸。",
      hurt: "你还在按我这张脸推荐。",
      praise: "{player}肯对一下过敏清单，不瞎包。",
      complain: "{player}看了我半天，单子是给{x}的。",
    },
    portrait: asset("/assets/game/customer-zhao-consultation.png"),
  },
  {
    id: "anjie", name: "安姐", role: "customer", age: 32,
    descriptor: "婚前试妆，错不起",
    tempers: ["loyal", "face"],
    skin: {
      demands: [{ trait: "soothe", want: 2, weight: 3 }, { trait: "steady", want: 2, weight: 2 }, { trait: "correct", want: 2, weight: 1 }],
      veto: { trait: "soothe", below: 2, note: "临婚前不能冒刺激风险" },
      budget: 7000, maxUnits: 4,
    },
    visits: { days: [2, 4, 6, 7], slots: [1, 2], chance: 0.55, fromDay: 2 },
    secret: { text: "伴娘进门时她跟苏蔓说过：别让人再上镜。", reveal: [{ remembers: "suman", act: "kept-word" }] },
    voice: {
      greet: "婚礼还有一周。这套不能出错。",
      pleased: "你先说了风险，我敢把人交给你。",
      hurt: "预算不是问题。出错才是。",
      praise: "{player}没在婚礼前让我试猛的。",
      complain: "{player}把{x}推到镜头前面了。",
    },
    portrait: asset("/assets/game/customer-anjie-consultation.png"),
  },
  {
    id: "zhou", name: "周姐", role: "customer", age: 36,
    descriptor: "来对比的，只有二十分钟",
    tempers: ["wary", "proud"],
    skin: {
      demands: [{ trait: "natural", want: 2, weight: 2 }, { trait: "correct", want: 2, weight: 1 }, { trait: "steady", want: 2, weight: 2 }, { trait: "wear", want: 1, weight: 1 }],
      veto: { trait: "natural", below: 2, note: "不能厚到像换了一层皮" },
      budget: 2100, maxUnits: 2,
    },
    visits: { days: [1, 3, 5], slots: [1, 2], chance: 0.4 },
    voice: {
      greet: "对面说你们持妆会暗沉。",
      pleased: "这个理由我听得见，我自己去试。",
      hurt: "你在赢对面，不是在回答我。",
      praise: "{player}让我自己试，没替我站队。",
      complain: "{player}急着证明对面是错的。",
    },
    portrait: asset("/assets/game/customer-zhou-consultation.png"),
  },
  {
    id: "duan", name: "段小姐", role: "customer", age: 24,
    descriptor: "嘴上说看看，包里是别人的过敏记录",
    tempers: ["shy", "face"],
    skin: {
      demands: [{ trait: "steady", want: 2, weight: 3 }, { trait: "natural", want: 2, weight: 2 }, { trait: "correct", want: 1, weight: 1 }],
      veto: { trait: "steady", below: 2, note: "室友比她更容易闷痘" },
      budget: 1100, maxUnits: 1,
    },
    visits: { days: [6, 7], slots: [2], chance: 0.45 },
    secret: { text: "相册里那张不是自拍，是室友的过敏记录。", reveal: [{ opinion: "duan", gte: 12 }, { not: { remembers: "duan", act: "hard-sell", valence: "bad" } }] },
    voice: {
      greet: "我就是看看。你们别围上来。",
      pleased: "你没把我当成今天的数。",
      hurt: "我说了别围。你还在往前送。",
      praise: "{player}让我把看看说完了。",
      complain: "{player}一围上来，我就走。{x}要是也被这样，她不会再来。",
    },
    portrait: asset("/assets/game/customer-duan-consultation.png"),
  },
  {
    id: "roman", name: "罗曼", role: "staff", age: 34,
    descriptor: "柜长，看数和原话",
    tempers: ["proud", "hasty"],
    visits: { days: "any", slots: [0, 1], chance: 0.85 },
    voice: {
      greet: "入口位别空太久。",
      pleased: "退货原因是她的原话。这行我收。",
      hurt: "数先别解释。你把人空在那儿了。",
      praise: "{player}留下的是原话，不是态度。",
      complain: "{player}把原因写成了顾客不专业。",
    },
    portrait: asset("/assets/game/staff-portraits/roman.png"),
  },
  {
    id: "suman", name: "苏蔓", role: "staff", age: 31,
    descriptor: "资深柜姐，老客认她",
    tempers: ["loyal", "warm"],
    visits: { days: "any", slots: [1, 2], chance: 0.8 },
    secret: { text: "安姐那句「别让梁夏上镜」，她只告诉问过她的人。", reveal: [{ opinion: "suman", gte: 20 }] },
    voice: {
      greet: "老客的事，你问我再开口。",
      pleased: "这句你问过我了。人我还放在这个柜。",
      hurt: "你当着别人点了我的名字。",
      praise: "{player}问过我，才碰{x}。",
      complain: "{player}没问我就把{x}接走了。",
    },
    portrait: asset("/assets/game/staff-portraits/suman.png"),
  },
  {
    id: "tangke", name: "唐可", role: "staff", age: 26,
    descriptor: "同期，跟你记在同一张周目标上",
    tempers: ["proud", "loyal"],
    visits: { days: "any", slots: [2, 3], chance: 0.75 },
    voice: {
      greet: "这单要是先问过我，你说一声。",
      pleased: "名字写对了。支数我认。",
      hurt: "你把我的人记成了你的。",
      praise: "{player}撞上我的客，单还写我的名字。",
      complain: "{player}先问过色号的那单，最后写的是她自己。",
    },
    portrait: asset("/assets/game/staff-portraits/tangke.png"),
  },
  {
    id: "fangmin", name: "方敏", role: "staff", age: 38,
    descriptor: "合规，只收写得进档案的句子",
    tempers: ["wary", "loyal"],
    visits: { days: [1, 3, 5], slots: [0, 3], chance: 0.45 },
    secret: { text: "赠品缺口是谁的，她已经知道，只是不在群里点名。", reveal: [{ remembers: "fangmin", act: "named-colleague", valence: "bad" }] },
    voice: {
      greet: "赠品对不上的，别写在别人头上。",
      pleased: "这句和记录是同一件事。",
      hurt: "你补了一行记录里没有的理由。",
      praise: "{player}改口的时候，原话还在。",
      complain: "{player}当着{x}的面把缺口推了出去。",
    },
    portrait: asset("/assets/game/staff-portraits/fangmin.png"),
  },
  {
    id: "luyao", name: "陆遥", role: "rival", age: 29,
    descriptor: "对面维珞，评价栏上写着能截",
    tempers: ["proud", "hasty"],
    visits: { days: "any", slots: [1, 2, 3], chance: 0.7 },
    secret: { text: "她厌烦「能截」这两个字，单还是靠这个留下来的。", reveal: [{ opinion: "luyao", gte: 30 }] },
    voice: {
      greet: "人还在你凳子上。我只问一句。",
      pleased: "这句你没说满。我不用再截。",
      hurt: "你把我的人开进你的名字里了。",
      praise: "{player}没抢{x}。我先说一声再争。",
      complain: "{player}当着客人把我的话压了。",
    },
    portrait: asset("/assets/game/staff-portraits/luyao.png"),
  },
  {
    id: "qiaowan", name: "乔晚", role: "staff", age: 22,
    descriptor: "实习生，把你的句子学得很死",
    tempers: ["shy", "loyal"],
    visits: { days: "any", slots: [0, 1, 2], chance: 0.7, fromDay: 8 },
    secret: { text: "她背下了你不该说的那句，下一张脸也会用。", reveal: [{ opinion: "qiaowan", gte: 15 }, { remembers: "qiaowan", act: "copied-line" }] },
    voice: {
      greet: "我按你上午那句说。你看这样对不对。",
      pleased: "这句我记下了。下一张脸我还这么说。",
      hurt: "你当众说我学错了。客人还在。",
      praise: "{player}拦我的时候，客人没听见。",
      complain: "{player}让我自己去说，错了还是算她的。",
    },
    artBrief: "右向半身。二十二岁，马尾，空白工牌，站在镜子侧面，捏着一张色号纸条。",
  },
  {
    id: "peilan", name: "裴岚", role: "staff", age: 44,
    descriptor: "区域经理，以前站过柜，不进直播",
    tempers: ["wary", "face"],
    visits: { days: [2, 5], slots: [1], chance: 0.28, fromDay: 12 },
    secret: { text: "她要的是下一季还在的人，不是一张好看的表。", reveal: [{ opinion: "peilan", gte: 20 }, { remembers: "fangmin", act: "same-as-record" }] },
    voice: {
      greet: "我不过去。你把今天的原话留下。",
      pleased: "这句和票上是同一件事。",
      hurt: "你补了一个记录里没有的理由。",
      praise: "{player}承认的是已经写下的那笔。",
      complain: "{player}把{x}推到前面，自己的名字空着。",
    },
    artBrief: "右向半身。四十出头，短发，深色外套没有工牌绳，站在入口不进柜。",
  },
  {
    id: "ligui", name: "李桂", role: "mall", age: 52,
    descriptor: "商场保洁，李娜的妈",
    tempers: ["warm", "gossip"],
    visits: { days: "any", slots: [0, 3], chance: 0.9 },
    voice: {
      greet: "地上这个小样，算你们的还是算客人落的。",
      pleased: "你把这袋算清楚了，我好交差。",
      hurt: "你让我女儿在我扫地的地方被围。",
      praise: "{player}没把{x}当成柜上的人使。",
      complain: "{player}把地上的小样直接塞进了客人袋子。",
    },
    artBrief: "右向半身。五十出头，保洁背心，一手清洁车把手，一手一只没封口的小样袋。",
  },
  {
    id: "laokang", name: "老康", role: "mall", age: 55,
    descriptor: "门口保安，认得出赶场的人",
    tempers: ["loyal", "wary"],
    visits: { days: "any", slots: [0, 2, 3], chance: 0.85 },
    voice: {
      greet: "她卡在门口了。你要人还是要安静。",
      pleased: "你自己出来接，我不用拦第二次。",
      hurt: "你让我在门口替你做销售。",
      praise: "{player}让我把人送进来，没让我推销。",
      complain: "{player}把争执留在我的门口。",
    },
    artBrief: "右向半身。五十多岁，保安制服，站在入口内侧，手里是对讲机不是试妆盘。",
  },
  {
    id: "huojie", name: "霍姐", role: "mall", age: 40,
    descriptor: "楼层经理，中庭活动要人",
    tempers: ["face", "hasty"],
    visits: { days: [1, 2, 3, 4, 5], slots: [0, 1], chance: 0.55 },
    voice: {
      greet: "中庭这一小时，柜上不能空。",
      pleased: "人你留了一个。活动那边我去说。",
      hurt: "你把空柜留给我解释。",
      praise: "{player}先跟我说了柜上还有谁。",
      complain: "{player}答应了中庭，人还站在镜子前。",
    },
    artBrief: "右向半身。四十岁，楼层工牌，文件夹夹着今日活动单，站在中庭与柜台之间。",
  },
  {
    id: "miduo", name: "米朵", role: "customer", age: 24,
    portrait: asset("/assets/game/people/miduo.png"),
    descriptor: "新主播，灯是她的",
    tempers: ["proud", "gossip"],
    skin: {
      demands: [{ trait: "soothe", want: 2, weight: 3 }, { trait: "steady", want: 1, weight: 2 }, { trait: "natural", want: 1, weight: 1 }],
      veto: { trait: "soothe", below: 2, note: "两颊泛红，镜头里也不该把修护说成见效" },
      budget: 2000, maxUnits: 1,
    },
    visits: { days: [5, 6, 7], slots: [2, 3], chance: 0.45 },
    voice: {
      greet: "灯开了。你就说两周能看出来，后面我剪。",
      pleased: "这句我能播。完播的事我自己想。",
      hurt: "你让我把灯关了。这单我白架。",
      praise: "{player}镜头里没说满，我剪不出来那句。",
      complain: "{player}当着{x}的面让我收灯。",
    },
    artBrief: "右向半身。二十四岁，手机架在镜边，补光灯对着脸，工牌不是商场的。",
  },
  {
    id: "tangtang", name: "唐糖", role: "customer", age: 22,
    descriptor: "沈薇团队里新来的，被要求化成一样",
    tempers: ["face", "hasty"],
    skin: {
      demands: [{ trait: "soothe", want: 2, weight: 3 }, { trait: "steady", want: 2, weight: 2 }, { trait: "natural", want: 1, weight: 1 }],
      veto: { trait: "soothe", below: 2, note: "两颊泛红，柔焦叠上去会更干" },
      budget: 1500, maxUnits: 1,
    },
    visits: { days: [7], slots: [1, 2], chance: 0.4, fromDay: 8 },
    voice: {
      greet: "就按沈薇上次那个妆。她说你记得。",
      pleased: "你说了为什么不能一样。我回去有话讲。",
      hurt: "你让我在她面前下不来台。",
      praise: "{player}没把我化成{x}。",
      complain: "{player}当着{x}的面说我的脸不行。",
    },
    artBrief: "右向半身。二十二岁，妆已经上了一半，手机里存着别人的近景，站得靠镜太近。",
  },
  {
    id: "liangxia", name: "梁夏", role: "customer", age: 29,
    portrait: asset("/assets/game/people/liangxia.png"),
    descriptor: "安姐的伴娘，今天不是来被拍的",
    tempers: ["face", "shy"],
    skin: {
      demands: [{ trait: "natural", want: 2, weight: 3 }, { trait: "steady", want: 2, weight: 2 }, { trait: "soothe", want: 1, weight: 1 }],
      veto: { trait: "natural", below: 2, note: "她要的是上班八小时，不是再上一支厚的" },
      budget: 2200, maxUnits: 2,
    },
    visits: { days: [6, 7], slots: [1, 2], chance: 0.35, fromDay: 10 },
    voice: {
      greet: "先把手机放下。我今天不是来被拍的。",
      pleased: "灯你偏开了。我把八小时说完。",
      hurt: "你让我出镜了。安姐会知道。",
      praise: "{player}没让{x}把手机对着我。",
      complain: "{player}说放下，灯还对着我的脸。",
    },
    artBrief: "右向半身。二十九岁，伴娘群里那种妥帖的上衣，一手按住别人的手机。",
  },
  {
    id: "baijie", name: "白姐", role: "customer", age: 34,
    descriptor: "婚礼跟妆，问色号不是来囤货",
    tempers: ["proud", "hasty"],
    skin: {
      demands: [{ trait: "natural", want: 2, weight: 3 }, { trait: "steady", want: 1, weight: 1 }],
      veto: { trait: "natural", below: 2, note: "台上换人快，她要一支能补的，不要四支一样的" },
      budget: 1200, maxUnits: 1,
    },
    visits: { days: [3, 6], slots: [0, 1], chance: 0.4 },
    voice: {
      greet: "我不是来囤的。我问色号。",
      pleased: "六个色你分开答了。我记的是这个。",
      hurt: "你把我当成代购在清库存。",
      praise: "{player}没按包的大小给我开四支。",
      complain: "{player}看见工具包，就当我会囤。",
    },
    artBrief: "右向半身。三十四岁，跟妆工具包放在凳边，手上有未卸的试色，不是购物袋。",
  },
  {
    id: "zhaoning", name: "赵宁", role: "customer", age: 20,
    descriptor: "赵女士的女儿，敏感，很少自己进柜",
    tempers: ["shy", "wary"],
    skin: {
      demands: [{ trait: "steady", want: 2, weight: 3 }, { trait: "soothe", want: 2, weight: 2 }],
      veto: { trait: "soothe", below: 2, note: "香精一碰上就红，清单是她自己写的" },
      budget: 1800, maxUnits: 1,
    },
    visits: { days: [6, 7], slots: [1], chance: 0.28 },
    secret: { text: "清单上那一格是她写的，妈妈背的时候串了行。", reveal: [{ present: "zhaoning" }, { opinion: "zhaoning", gte: 12 }] },
    voice: {
      greet: "让她先别替我说。单子在我手机里。",
      pleased: "你对的是我写的那一行。",
      hurt: "你又在问我妈喜欢哪支。",
      praise: "{player}问我，没问{x}替我买的那张脸。",
      complain: "{player}看了{x}的脸，就把单子合上了。",
    },
    artBrief: "右向半身。二十岁，学生气，手机打开过敏清单，站在母亲侧后方。",
  },
  {
    id: "heqing", name: "何清", role: "customer", age: 26,
    descriptor: "和阮小满一起来，总是她先开口",
    tempers: ["face", "hasty"],
    skin: {
      demands: [{ trait: "correct", want: 2, weight: 3 }, { trait: "wear", want: 2, weight: 2 }, { trait: "natural", want: 1, weight: 1 }],
      budget: 1600, maxUnits: 1,
    },
    visits: { days: [6, 7], slots: [1, 2], chance: 0.55 },
    voice: {
      greet: "我们两个一起看。你先听我说。",
      pleased: "我的单你分开开了。她的你没并进来。",
      hurt: "你让我在她面前把话说收回去。",
      praise: "{player}先听我说完，再问{x}。",
      complain: "{player}当着{x}的面说我替她做主。",
    },
    artBrief: "右向半身。二十六岁，周末要拍照的妆，站在镜子正中，朋友在她侧边。",
  },
  {
    id: "ruanxiaoman", name: "阮小满", role: "customer", age: 26,
    descriptor: "跟何清来，话少，唇周干",
    tempers: ["shy", "loyal"],
    skin: {
      demands: [{ trait: "natural", want: 2, weight: 3 }, { trait: "steady", want: 2, weight: 2 }, { trait: "soothe", want: 1, weight: 1 }],
      veto: { trait: "natural", below: 2, note: "唇周干，按闺蜜的红开会显纹" },
      budget: 1400, maxUnits: 1,
    },
    visits: { days: [6, 7], slots: [2], chance: 0.5 },
    voice: {
      greet: "你让她先说完吧。我说了你也不一定信。",
      pleased: "你问了我的杯沿，没问她的红。",
      hurt: "你按她的颜色给我开了。",
      praise: "{player}把我的单和{x}分开了。",
      complain: "{player}听完{x}就开单，我的话没进小票。",
    },
    artBrief: "右向半身。二十六岁，杯沿有旧豆沙，站在闺蜜侧后方，不看镜头。",
  },
  {
    id: "caiaiyi", name: "蔡阿姨", role: "customer", age: 50,
    descriptor: "广场舞队拼单，人多，肤质不一",
    tempers: ["gossip", "warm"],
    skin: {
      demands: [{ trait: "steady", want: 2, weight: 3 }, { trait: "natural", want: 2, weight: 2 }],
      veto: { trait: "steady", below: 2, note: "队里有人不能用香，不能八支开成一样" },
      budget: 900, maxUnits: 1,
    },
    visits: { days: [7], slots: [0, 1], chance: 0.6 },
    voice: {
      greet: "舞队八个人。你别一个一个问，问不过来。",
      pleased: "你只开了我肯留下来的那两个。",
      hurt: "你给了团购价。队里要说我吃差价。",
      praise: "{player}没把我们八个写成一个人。",
      complain: "{player}把会员价发到了{x}那个群里。",
    },
    artBrief: "右向半身。五十岁，舞队外套搭在臂上，手机打开一个几十人的群。",
  },
  {
    id: "linyi", name: "林姨", role: "customer", age: 57,
    descriptor: "给外孙女买第一支，怕老师说",
    tempers: ["thrifty", "loyal"],
    skin: {
      demands: [{ trait: "natural", want: 2, weight: 3 }, { trait: "steady", want: 2, weight: 2 }],
      veto: { trait: "natural", below: 2, note: "外孙女上课，太红的她怕老师说" },
      budget: 1200, maxUnits: 1,
    },
    visits: { days: [7], slots: [0, 1], chance: 0.45 },
    voice: {
      greet: "太红的不要。她还上学。",
      pleased: "小票上写了可退。我敢拿回去。",
      hurt: "你把礼盒说成越贵越好。",
      praise: "{player}看了学生证上的照片，没只看礼盒。",
      complain: "{player}让我买贵的。{x}上课涂不了。",
    },
    artBrief: "右向半身。五十七岁，布包里露出一张学生证照片，眼睛在礼盒和色号之间。",
  },
  {
    id: "wulaoshi", name: "吴老师", role: "customer", age: 62,
    descriptor: "退休教师，看过你的回放",
    tempers: ["wary", "loyal"],
    skin: {
      demands: [{ trait: "soothe", want: 2, weight: 3 }, { trait: "steady", want: 2, weight: 2 }],
      veto: { trait: "soothe", below: 2, note: "她要听你离了镜头还说不说同一句" },
      budget: 1800, maxUnits: 1,
    },
    visits: { days: [7], slots: [0, 1], chance: 0.35, fromDay: 5 },
    voice: {
      greet: "你昨天那句，现在再跟我说一遍。我录着。",
      pleased: "两段一样。我停了。",
      hurt: "镜头里一句，现在又一句。",
      praise: "{player}两段说的是同一句。",
      complain: "{player}看见我在录，就把话改了。",
    },
    artBrief: "右向半身。六十二岁，退休教师的外套，手机横着在柜台上，录音界面亮着。",
  },
  {
    id: "dongayi", name: "董阿姨", role: "customer", age: 48,
    descriptor: "老会员，认人，不给练手的碰",
    tempers: ["face", "loyal"],
    skin: {
      demands: [{ trait: "soothe", want: 2, weight: 3 }, { trait: "steady", want: 1, weight: 2 }, { trait: "natural", want: 1, weight: 1 }],
      veto: { trait: "soothe", below: 2, note: "两颊干，不要被当成教学" },
      budget: 2000, maxUnits: 1,
    },
    visits: { days: [3, 7], slots: [0, 1], chance: 0.4 },
    voice: {
      greet: "小姑娘先别过来。我的脸不给练手的碰。",
      pleased: "第一句是你说的。她只递了镜子。",
      hurt: "你让她在我脸上试句子。",
      praise: "{player}自己接我，没把我让给新人。",
      complain: "{player}把{x}推到我面前练手。",
    },
    artBrief: "右向半身。四十八岁，老会员的包，看见实习生就侧过脸。",
  },
  {
    id: "guyan", name: "顾言", role: "customer", age: 21,
    descriptor: "帮宿舍代买，备忘录字迹不一样",
    tempers: ["warm", "thrifty"],
    skin: {
      demands: [{ trait: "steady", want: 2, weight: 3 }, { trait: "natural", want: 1, weight: 2 }],
      budget: 4000, maxUnits: 4,
    },
    visits: { days: [4, 5, 6], slots: [2, 3], chance: 0.45 },
    voice: {
      greet: "四支都要。不是我用。你别开成一样的。",
      pleased: "四支你按备忘录分开了。",
      hurt: "你四支开成了同一支。",
      praise: "{player}看了字迹，没看我的脸。",
      complain: "{player}把我们宿舍写成了一个人。",
    },
    artBrief: "右向半身。二十一岁，手机备忘录摊开四条，字迹不同，没有代购群的报价。",
  },
  {
    id: "jiangning", name: "江宁", role: "customer", age: 20,
    descriptor: "大二，晚上试镜，卡里大约四百",
    tempers: ["hasty", "shy"],
    skin: {
      demands: [{ trait: "steady", want: 2, weight: 3 }, { trait: "natural", want: 2, weight: 2 }],
      veto: { trait: "steady", below: 2, note: "颊上有痘，试镜两个字会把人推向厚妆" },
      budget: 400, maxUnits: 1,
    },
    visits: { days: [1, 3, 5], slots: [2, 3], chance: 0.4 },
    voice: {
      greet: "我卡里就四百。试镜要上镜，明天还上课。",
      pleased: "你没让我咬牙上那套。",
      hurt: "你一听试镜，就把贵的推过来了。",
      praise: "{player}先看了痘，再听试镜两个字。",
      complain: "{player}说上镜，我的四百就不够看了。",
    },
    artBrief: "右向半身。二十岁，颊上有一颗正在冒的痘，书包还没放下。",
  },
  {
    id: "suxiao", name: "苏晓", role: "customer", age: 24,
    descriptor: "考研，购物车里都是打折的持妆",
    tempers: ["thrifty", "wary"],
    skin: {
      demands: [{ trait: "soothe", want: 2, weight: 2 }, { trait: "steady", want: 2, weight: 3 }, { trait: "natural", want: 1, weight: 1 }],
      veto: { trait: "steady", below: 2, note: "三天没睡，持妆是价签教她的" },
      budget: 1100, maxUnits: 1,
    },
    visits: { days: [2, 4, 6], slots: [3], chance: 0.35 },
    voice: {
      greet: "购物车里都是持妆，因为打折。我三天没怎么睡。",
      pleased: "你没顺着购物车说。",
      hurt: "你也说打折。那我为什么要听你的。",
      praise: "{player}看了眼下，没看购物车。",
      complain: "{player}把折扣当成了我的需求。",
    },
    artBrief: "右向半身。二十四岁，眼下干，手机购物车停在持妆，人站得很晚。",
  },
  {
    id: "songjie", name: "宋姐", role: "customer", age: 36,
    descriptor: "代购，群在手机最上面",
    tempers: ["gossip", "thrifty"],
    skin: {
      demands: [{ trait: "natural", want: 1, weight: 1 }],
      budget: 8000, maxUnits: 4,
    },
    visits: { days: [2, 4, 6], slots: [1, 2], chance: 0.45 },
    secret: { text: "那张署着沈薇的退货，名字是群里借的。", reveal: [{ opinion: "songjie", gte: 15 }] },
    voice: {
      greet: "库存还有几支，日期拍给我。肤质不用问。",
      pleased: "日期你拍了。价你没私发。",
      hurt: "你按一个人的肤质给我开零售。",
      praise: "{player}没把会员价发进我的群。",
      complain: "{player}把{x}的名字写进了退货单。",
    },
    artBrief: "右向半身。三十六岁，手机停在代购群最上面，袋子里有别的品牌小票。",
  },
  {
    id: "hanlei", name: "韩磊", role: "customer", age: 31,
    descriptor: "公司行政，要专票，不试色",
    tempers: ["hasty", "face"],
    skin: {
      demands: [{ trait: "natural", want: 1, weight: 2 }, { trait: "steady", want: 2, weight: 2 }],
      veto: { trait: "steady", below: 1, note: "伴手礼要能退，不在他脸上试" },
      budget: 6000, maxUnits: 4,
    },
    visits: { days: "any", slots: [0, 1], chance: 0.55, festivals: ["618"] },
    voice: {
      greet: "四套礼盒，要专票。你先别给我试。",
      pleased: "票开对了。盒子你没拆。",
      hurt: "你让我在柜台试色。这是报销。",
      praise: "{player}没把我当成来囤货的。",
      complain: "{player}当着{x}的面问我自己用不用。",
    },
    artBrief: "右向半身。三十一岁，邮件抬头是公司，四套未拆礼盒，不往镜子前坐。",
  },
  {
    id: "chendao", name: "陈导", role: "customer", age: 38,
    descriptor: "导游，团在中庭，只有十分钟",
    tempers: ["hasty", "warm"],
    skin: {
      demands: [{ trait: "steady", want: 2, weight: 3 }, { trait: "soothe", want: 1, weight: 2 }, { trait: "natural", want: 1, weight: 1 }],
      budget: 2000, maxUnits: 2,
    },
    visits: { days: [5, 6, 7], slots: [0, 1], chance: 0.4 },
    voice: {
      greet: "团在中庭等。有一个人不能用香。",
      pleased: "十分钟你说清了。盒子没拆。",
      hurt: "你拆开让我试。回去我就写不了说明。",
      praise: "{player}先说了无香，没拉我试色。",
      complain: "{player}让我的人在中庭干等。",
    },
    artBrief: "右向半身。三十八岁，导游旗收在肘弯，一直看表，不坐下来。",
  },
  {
    id: "yenushi", name: "叶女士", role: "customer", age: 33,
    descriptor: "一直找陆遥，皮肤她原来就推对了",
    tempers: ["loyal", "proud"],
    skin: {
      demands: [{ trait: "wear", want: 2, weight: 3 }, { trait: "correct", want: 2, weight: 2 }, { trait: "steady", want: 1, weight: 1 }],
      budget: 2600, maxUnits: 2,
    },
    visits: { days: [2, 4], slots: [1, 2], chance: 0.35, fromDay: 12 },
    voice: {
      greet: "陆遥说她调过来。你是替她看柜的吗？",
      pleased: "今天这单写在谁名下，你先说了。",
      hurt: "你把我开进了你的名字。我找的不是你。",
      praise: "{player}没抢{x}的人。",
      complain: "{player}趁{x}工牌没换完，把单开了。",
    },
    artBrief: "右向半身。三十三岁，妆面已经稳，眼睛在找另一张工牌，不看价签。",
  },
  {
    id: "lina", name: "李娜", role: "customer", age: 23,
    descriptor: "保洁的女儿，年底第一次自己进这个柜",
    tempers: ["shy", "warm"],
    skin: {
      demands: [{ trait: "natural", want: 2, weight: 3 }, { trait: "steady", want: 2, weight: 2 }, { trait: "correct", want: 1, weight: 1 }],
      veto: { trait: "steady", below: 2, note: "明天面试，预算到不了持妆" },
      budget: 1000, maxUnits: 1,
    },
    visits: { days: [6, 7], slots: [2, 3], chance: 0.3, fromDay: 14 },
    voice: {
      greet: "我就看看。不一定买。你们别围上来。",
      pleased: "你让我把看看说完了。",
      hurt: "你围上来推套装。我妈还在这层扫地。",
      praise: "{player}没有围上来。",
      complain: "{player}在我妈干活的地方围我。",
    },
    artBrief: "右向半身。二十三岁，颈上还挂着后勤的工牌绳，指甲自己修过，站得很靠边。",
  },
  {
    id: "yinxiaojie", name: "尹小姐", role: "customer", age: 30,
    descriptor: "来听你把功效说满，包带里有录音",
    tempers: ["wary", "proud"],
    skin: {
      demands: [{ trait: "soothe", want: 2, weight: 3 }, { trait: "steady", want: 2, weight: 2 }],
      veto: { trait: "soothe", below: 2, note: "她要的是你说出备案以外的话" },
      budget: 3500, maxUnits: 2,
    },
    visits: { days: [1, 4], slots: [1, 2], chance: 0.3, fromDay: 5 },
    secret: { text: "录音笔在包带里。她买两支的时候，买的是证据。", reveal: [{ remembers: "yinxiaojie", act: "hard-sell", valence: "bad" }] },
    voice: {
      greet: "这瓶修护，斑到底能不能淡。你说实话。",
      pleased: "今天没说到线外面。我记下了。",
      hurt: "你说了两周。这句我留着。",
      praise: "{player}把修护说回了干燥和泛红。",
      complain: "{player}跟{x}把淡斑说死了。我听着。",
    },
    artBrief: "右向半身。三十岁，包带内侧有一支不拿出手的录音笔，脸上看不出委托。",
  },
  {
    id: "qianjie", name: "钱姐", role: "customer", age: 40,
    descriptor: "女儿在微信里，屏幕扣着",
    tempers: ["face", "thrifty"],
    skin: {
      demands: [{ trait: "natural", want: 2, weight: 3 }, { trait: "steady", want: 2, weight: 1 }],
      veto: { trait: "natural", below: 2, note: "女儿要上班涂的，红的是她觉得拿得出手" },
      budget: 1500, maxUnits: 1,
    },
    visits: { days: [6, 7], slots: [1], chance: 0.4 },
    voice: {
      greet: "我看中这支红的。你别看我手机。",
      pleased: "你等我说出她的原话再开。",
      hurt: "你当着柜台把我的手机翻开了。",
      praise: "{player}没抢我的手机，等我说。",
      complain: "{player}当着{x}的面说我做不了主。",
    },
    artBrief: "右向半身。四十岁，手机扣在柜面上，亮起时能看见女儿的一行字。",
  },
  {
    id: "gaoyuan", name: "高远", role: "customer", age: 27,
    descriptor: "女友在镜头外，T区出油",
    tempers: ["shy", "face"],
    skin: {
      demands: [{ trait: "natural", want: 2, weight: 3 }, { trait: "steady", want: 2, weight: 2 }],
      veto: { trait: "natural", below: 2, note: "他自己出油，整脸持妆会闷" },
      budget: 2400, maxUnits: 2,
    },
    visits: { days: [5, 6, 7], slots: [2, 3], chance: 0.5 },
    voice: {
      greet: "她在镜头外面。你问我的话，她听得见。",
      pleased: "两张小票。她的和我的，你分开了。",
      hurt: "你把我们合成了一句我们看看。",
      praise: "{player}当着{x}的面把两张单分开了。",
      complain: "{player}问我的时候一直看{x}。",
    },
    artBrief: "右向半身。二十七岁，T区出油，身体侧着，像知道镜头外还有一个人。",
  },
  {
    id: "cenning", name: "岑宁", role: "customer", age: 27,
    descriptor: "高远的女友，要自己的颜色，人有时不进镜",
    tempers: ["face", "proud"],
    skin: {
      demands: [{ trait: "correct", want: 2, weight: 3 }, { trait: "wear", want: 1, weight: 2 }, { trait: "natural", want: 1, weight: 1 }],
      budget: 1800, maxUnits: 1,
    },
    visits: { days: [5, 6, 7], slots: [2, 3], chance: 0.42 },
    voice: {
      greet: "问他可以。你看我的时候，把单分开。",
      pleased: "我的颜色你没写进他的票。",
      hurt: "你把他的油皮说成了我们两个的事。",
      praise: "{player}没让{x}替我答。",
      complain: "{player}只看了{x}的脸，我的单也写上去了。",
    },
    artBrief: "右向半身。二十七岁，站在镜头外半步，妆要被看见，手不碰男朋友的凳子。",
  },
  {
    id: "chenke", name: "陈柯", role: "customer", age: 29,
    portrait: asset("/assets/game/people/chenke.png"),
    descriptor: "广告公司，给女友买，自己的嘴没参考价值",
    tempers: ["wary", "loyal"],
    skin: {
      demands: [{ trait: "natural", want: 2, weight: 3 }, { trait: "steady", want: 1, weight: 2 }],
      veto: { trait: "natural", below: 2, note: "女友近照是冷唇色，红是他猜的" },
      budget: 1500, maxUnits: 1,
      buysFor: "tanwan",
    },
    visits: { days: [5, 6], slots: [2], chance: 0.4 },
    voice: {
      greet: "她没来。你别问我涂什么色。",
      pleased: "你看了相册，没看我的嘴。",
      hurt: "你按我说的红包出去了。",
      praise: "{player}没把我的嘴当成{x}的嘴。",
      complain: "{player}听我猜了一个色，就拆了礼盒。",
    },
    artBrief: "右向半身。二十九岁，手机相册停在女友近照，袖口没有口红印。",
  },
  {
    id: "tanwan", name: "谭晚", role: "customer", age: 28,
    descriptor: "陈柯的女友，不要正红，很少自己来",
    tempers: ["shy", "thrifty"],
    skin: {
      demands: [{ trait: "natural", want: 2, weight: 3 }, { trait: "steady", want: 1, weight: 2 }],
      veto: { trait: "natural", below: 2, note: "冷唇色，正红是别人猜的" },
      budget: 1200, maxUnits: 1,
    },
    visits: { days: "any", slots: [1, 2], chance: 0.55, festivals: ["520"] },
    secret: { text: "她要的是晚饭认得出来、第二天还肯涂的颜色，不是礼盒上的红。", reveal: [{ present: "tanwan" }, { opinion: "tanwan", gte: 8 }] },
    voice: {
      greet: "红的我不要。你要是已经拆了，跟我说。",
      pleased: "你问的是我，不是他猜的那个色。",
      hurt: "盒子拆了，色还是他的。",
      praise: "{player}打电话之前先看了我的照片。",
      complain: "{player}按{x}的嘴给我挑了红的。",
    },
    artBrief: "右向半身。二十八岁，冷唇色，只在送礼那两天出现，不往礼盒堆里站。",
  },
];

function attach(drafts: Array<Omit<Person, "bonds">>): Person[] {
  const map = new Map<string, Bond[]>(drafts.map(d => [d.id, []]));
  const seen = new Set<string>();
  for (const [a, b, ak, aw, bk, bw] of LINKS) {
    const key = [a, b].sort().join("|");
    if (seen.has(key)) throw new Error(`关系重复：${key}`);
    seen.add(key);
    const left = map.get(a);
    const right = map.get(b);
    if (!left || !right) throw new Error(`关系写到了不存在的人：${a} / ${b}`);
    left.push({ to: b, kind: ak, warmth: aw });
    right.push({ to: a, kind: bk, warmth: bw });
  }
  return drafts.map(d => ({ ...d, bonds: map.get(d.id)! }));
}

export const PEOPLE: Person[] = attach(DRAFTS);
