import type { Employee, GameState } from './types';

const initialEmployees: Employee[] = [
  {
    id: 'ceo',
    name: '沈知行',
    age: 39,
    role: 'CEO',
    personality: '果断、结果导向',
    ability: 88,
    ambition: 94,
    stress: 62,
    satisfaction: 74,
    quitRisk: 3,
    currentThought: '这个季度必须证明增长故事。',
    currentTask: '敲定下一阶段公司战略',
    zone: 'ceo-office',
    relationships: [
      { targetId: 'tech_lead', value: 42 },
      { targetId: 'sales_lead', value: 55 },
      { targetId: 'finance', value: 36 },
    ],
  },
  {
    id: 'tech_lead',
    name: '顾言',
    age: 35,
    role: '技术负责人',
    personality: '冷静、技术理想主义',
    ability: 91,
    ambition: 71,
    stress: 58,
    satisfaction: 68,
    quitRisk: 14,
    currentThought: '技术债已经不能再拖了。',
    currentTask: '评审新一代模型服务架构',
    zone: 'product-dev',
    relationships: [
      { targetId: 'ceo', value: 31 },
      { targetId: 'backend_engineer', value: 61 },
      { targetId: 'product_manager', value: -8 },
    ],
  },
  {
    id: 'product_manager',
    name: '林薇',
    age: 31,
    role: '产品经理',
    personality: '强势、敏锐',
    ability: 83,
    ambition: 86,
    stress: 66,
    satisfaction: 63,
    quitRisk: 19,
    currentThought: '需求不改，用户数据就不会变好。',
    currentTask: '推进企业版工作台上线',
    zone: 'meeting-room',
    relationships: [
      { targetId: 'backend_engineer', value: -22 },
      { targetId: 'ui_designer', value: 37 },
      { targetId: 'ceo', value: 28 },
    ],
  },
  {
    id: 'backend_engineer',
    name: '周岩',
    age: 29,
    role: '后端工程师',
    personality: '谨慎、务实',
    ability: 86,
    ambition: 54,
    stress: 72,
    satisfaction: 57,
    quitRisk: 28,
    currentThought: '又改需求的话，这个版本肯定要炸。',
    currentTask: '修复计费服务并发问题',
    zone: 'product-dev',
    relationships: [
      { targetId: 'tech_lead', value: 61 },
      { targetId: 'product_manager', value: -18 },
      { targetId: 'frontend_engineer', value: 45 },
    ],
  },
  {
    id: 'frontend_engineer',
    name: '陈野',
    age: 27,
    role: '前端工程师',
    personality: '直接、追求体验',
    ability: 82,
    ambition: 63,
    stress: 55,
    satisfaction: 71,
    quitRisk: 17,
    currentThought: '这次交互终于像个成熟产品了。',
    currentTask: '完成数据看板交互',
    zone: 'product-dev',
    relationships: [
      { targetId: 'ui_designer', value: 58 },
      { targetId: 'backend_engineer', value: 39 },
      { targetId: 'product_manager', value: 12 },
    ],
  },
  {
    id: 'ui_designer',
    name: '乔语',
    age: 26,
    role: 'UI设计师',
    personality: '敏感、有审美坚持',
    ability: 84,
    ambition: 69,
    stress: 48,
    satisfaction: 76,
    quitRisk: 12,
    currentThought: '别再让人把设计稿当素材库了。',
    currentTask: '完善新版本视觉规范',
    zone: 'product-dev',
    relationships: [
      { targetId: 'frontend_engineer', value: 64 },
      { targetId: 'product_manager', value: 31 },
    ],
  },
  {
    id: 'sales_lead',
    name: '韩峰',
    age: 36,
    role: '销售负责人',
    personality: '进取、擅长谈判',
    ability: 87,
    ambition: 92,
    stress: 64,
    satisfaction: 67,
    quitRisk: 16,
    currentThought: '那个头部客户绝不能丢。',
    currentTask: '推进年度最大合同签约',
    zone: 'sales-area',
    relationships: [
      { targetId: 'ceo', value: 55 },
      { targetId: 'sales', value: 47 },
      { targetId: 'product_manager', value: 8 },
    ],
  },
  {
    id: 'sales',
    name: '许乐',
    age: 25,
    role: '销售',
    personality: '外向、抗压',
    ability: 75,
    ambition: 78,
    stress: 69,
    satisfaction: 65,
    quitRisk: 23,
    currentThought: '再跟进两次，客户也许会松口。',
    currentTask: '跟进六家试用客户',
    zone: 'sales-area',
    relationships: [
      { targetId: 'sales_lead', value: 52 },
      { targetId: 'operations', value: 29 },
    ],
  },
  {
    id: 'operations',
    name: '唐糖',
    age: 28,
    role: '运营',
    personality: '活跃、善于沟通',
    ability: 79,
    ambition: 68,
    stress: 52,
    satisfaction: 73,
    quitRisk: 13,
    currentThought: '今天的用户反馈有点不对劲。',
    currentTask: '策划客户增长活动',
    zone: 'open-office',
    relationships: [
      { targetId: 'product_manager', value: 36 },
      { targetId: 'sales', value: 41 },
      { targetId: 'intern', value: 48 },
    ],
  },
  {
    id: 'hr',
    name: '苏晴',
    age: 32,
    role: 'HR',
    personality: '温和、洞察力强',
    ability: 81,
    ambition: 57,
    stress: 44,
    satisfaction: 72,
    quitRisk: 10,
    currentThought: '最近找我聊天的人明显变多了。',
    currentTask: '完成季度员工访谈',
    zone: 'reception',
    relationships: [
      { targetId: 'ceo', value: 33 },
      { targetId: 'finance', value: 46 },
      { targetId: 'intern', value: 62 },
    ],
  },
  {
    id: 'finance',
    name: '赵辰',
    age: 34,
    role: '财务',
    personality: '稳健、风险厌恶',
    ability: 85,
    ambition: 48,
    stress: 61,
    satisfaction: 69,
    quitRisk: 11,
    currentThought: '照这个烧钱速度，现金会很难看。',
    currentTask: '更新未来六个月现金流',
    zone: 'open-office',
    relationships: [
      { targetId: 'ceo', value: 27 },
      { targetId: 'hr', value: 51 },
      { targetId: 'sales_lead', value: 6 },
    ],
  },
  {
    id: 'intern',
    name: '陆一然',
    age: 22,
    role: '实习生',
    personality: '好奇、容易紧张',
    ability: 61,
    ambition: 74,
    stress: 39,
    satisfaction: 82,
    quitRisk: 8,
    currentThought: '大家说话怎么都像有潜台词？',
    currentTask: '整理竞品功能清单',
    zone: 'pantry',
    relationships: [
      { targetId: 'hr', value: 58 },
      { targetId: 'operations', value: 53 },
      { targetId: 'product_manager', value: 11 },
    ],
  },
];

export function createInitialState(): GameState {
  return {
    day: 1,
    date: '2026-08-10',
    company: {
      cash: 420,
      morale: 72,
      conflict: 24,
      businessPressure: 58,
      quitRisk: 18,
      bossSatisfaction: 67,
    },
    employees: structuredClone(initialEmployees),
    todayEvents: [],
    pendingGodEvent: '',
  };
}
